apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: fib-client
          image: wendyi/fib-client:v1
          ports:
            - containerPort: 3000

